# Generated by Django 2.2.13 on 2020-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_type', models.CharField(max_length=255)),
                ('movie_showtime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
